[package]
name = "tracer-rs"
version = "0.1.0"
authors = ["Thomas Lambertz <mail@thomaslambertz.de>"]
license = "MIT/Apache-2.0"
edition = "2018"
build = "build.rs"

[features]
# controlls whether the stdlib is build with cargo -Z build-std=std,core,alloc,panic_abort
buildstd = []

[lib]
crate-type = ['rlib']
