[package]
name = "rftrace-frontend-ffi"
version = "0.1.0"
authors = ["Thomas Lambertz <mail@thomaslambertz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rftrace-frontend = {path="../rftrace-frontend"}
