name: CI

on:
  push:
  pull_request:
  merge_group:

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  c:
    name: C
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/c
    steps:
      - uses: actions/checkout@v4
      - name: Install uftrace
        run: |
          sudo apt-get update
          sudo apt-get install uftrace
      - uses: mkroening/rust-toolchain-toml@main
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-11-01
          components: llvm-tools
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Build
        run: make
      - name: Run
        run: |
          mkdir tracedir
          ./test
      - name: Replay
        run: uftrace replay --data=tracedir --output-fields=tid | tee ci.snap
      - name: Compare to snapshot
        run: diff ci.snap out.snap

  rust:
    name: Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/rust
    steps:
      - uses: actions/checkout@v4
      - name: Install uftrace
        run: |
          sudo apt-get update
          sudo apt-get install uftrace
      - uses: mkroening/rust-toolchain-toml@main
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-11-01
          components: llvm-tools
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Build
        run: cargo +nightly-2023-11-01 rustc -- -Zinstrument-mcount -C passes="ee-instrument<post-inline>"
      - name: Run
        run: |
          mkdir tracedir
          ../../target/debug/rftrace-rs-test
      - name: Replay
        run: uftrace replay --data=tracedir --output-fields=tid | tee ci.snap
      - name: Compare to snapshot
        run: diff ci.snap out.snap
